//配置文件的定义
module.exports = {
    menuBar:{
        backgroundColor:"#323b4c",//背景色
        defaultColor:"#767f90",//默认菜单颜色
        selectedColor:"#b11b27",//菜单选中颜色

        //使用字体图标自动生成图片，省去了开发者自己制作多张图的问题
        iconFontFrom:"/native/iconfont.ttf",

        menus:[{
            text:'首页',
            icon:'0xe64e',
            view:"index",
        },{
            text:'行情',
            icon:'0xe6d2',
            view:"market",
        },{
            text:'交易',
            icon:'0xe6a7',
            view:"trade",
        },{
            text:'理财',
            icon:'0xe696',
            view:"financing",
        },{
            text:'我的',
            icon:'0xe746',
            view:"account",
        }]
    },
    navBar:{
        backgroundColor:"#de302f",
        titleColor:"#ffffff",
        buttonColor:"#ffffff"
    },
    views:{
        "index":{
            url:"http://192.168.120.98:3000/app.native.js#/index",
            navBar:{
                type:"0"
            }
        },
        "market":{
            url:"http://192.168.120.98:3000/app.native.js#/market/hushen",
            navBar:{
                title:"行情"
            }
        },
        "trade":{
            url:"http://192.168.120.98:3000/app.native.js#/trade",
            navBar:{
                title:"交易"
            }
        },
        "financing":{
            url:"http://192.168.120.98:3000/app.native.js#/financing",
            navBar:{
                type:"0"
            }
        },
        "account":{
            url:"http://192.168.120.98:3000/app.native.js#/account",
            navBar:{
                type:"0"               
            }
        }       
    }
};